export default {
  env: {
    NEXT_PUBLIC_SUPABASE_URL: "https://avumdybwfgecunwbjtlj.supabase.co",
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dW1keWJ3ZmdlY3Vud2JqdGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MzAxOTcsImV4cCI6MjA3NDUwNjE5N30.1d0e-28UFl24Wa2sm9IG7b86Yoh8ln_EhRz5u8U_U5I",
    NEXT_PUBLIC_SITE_URL: "http://localhost:3000",
    SUPABASE_SERVICE_ROLE_KEY:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dW1keWJ3ZmdlY3Vud2JqdGxqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODkzMDE5NywiZXhwIjoyMDc0NTA2MTk3fQ.BMd4TcTKEFwdbnC68JNRMUY-pFRGNeGVkli5_dKVNrs",
    NEXT_PUBLIC_USE_NEW_DASHBOARD: "true",
  },
}
